# Generated by Django 5.0 on 2024-02-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Cliente'), (2, 'Vendedor'), (3, 'Administrador')], default=3),
        ),
    ]
