# Generated by Django 5.0 on 2024-02-26 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la cancha')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por hora')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fields', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Cancha',
                'verbose_name_plural': 'Canchas',
            },
        ),
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media_images', verbose_name='Imagen')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'imagen',
                'verbose_name_plural': 'imagenes',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='business', verbose_name='Imágen principal')),
                ('latitude', models.FloatField(default=0.0, verbose_name='Longitud')),
                ('longitude', models.FloatField(default=0.0, verbose_name='Latitud')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('reference', models.TextField(blank=True, null=True, verbose_name='Referencia')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Fech. actualizado')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.department', verbose_name='Departamento')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.district', verbose_name='Distrito')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.province', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'negocio',
                'verbose_name_plural': 'Negocios',
            },
        ),
    ]
